# Generated by Django 4.1 on 2022-12-11 16:51

from django.db import migrations, models
import django.db.models.deletion
import mailing.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[mailing.validators.PhoneNumberValidator()], verbose_name='Номер телефона')),
                ('phone_code', models.CharField(editable=False, max_length=3, verbose_name='Код мобильного оператора')),
                ('timezone', models.CharField(max_length=3, verbose_name='Часовой пояс')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='Тег')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Дата начала')),
                ('finished_at', models.DateTimeField(verbose_name='Дата окончани')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('filter', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('postponed', 'Postponed'), ('not_sent', 'Not sent')], default='Sent', max_length=9, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
