version: '3.8'
services:
  db:
    image: postgres:13.2
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: organizzzzm/fabrique:v.1.0.12.2022
    restart: always
    volumes:
      - django_static:/app/django_static/
    depends_on:
      - db
    env_file:
      - ../.env
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py makemigrations --no-input
        python3 manage.py migrate --no-input
        python3 manage.py collectstatic --no-input
        gunicorn --bind 0.0.0.0:8000 fabrique.wsgi:application

  nginx:
    image: nginx:1.22
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/var/html/django_static/
    depends_on:
      - backend

volumes:
  media_value:
  django_static:
